### PR TITLE
Better handling of unicode prefix_dir on OSX.

### LINKED ISSUE #45: TypeError on Python3, OSX
The retext project uses pyenchant and somehow the version i have installed seems to fail. 

```
python3 ./retext.py                                                                            
Traceback (most recent call last):
  File "./retext.py", line 24, in <module>
    from ReText import datadirs, globalSettings
  File "/Users/techdragon/dev/sourceforge.com/retext-git/ReText/__init__.py", line 23, in <module>
    import enchant
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/enchant/__init__.py", line 92, in <module>
    from enchant import _enchant as _e
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/enchant/_enchant.py", line 121, in <module>
    prefix_dir.contents = c_char_p(e_dir)
TypeError: bytes or integer address expected instead of str instance
```

Double checking, the issue is with the python wrapper as i can't get it to work using the wheel just by itself in the python interpreter.

```
python3                                                                                          1   master
Python 3.4.0 (v3.4.0:04f714765c13, Mar 15 2014, 23:02:41)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/enchant/__init__.py", line 92, in <module>
    from enchant import _enchant as _e
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/enchant/_enchant.py", line 121, in <module>
    prefix_dir.contents = c_char_p(e_dir)
TypeError: bytes or integer address expected instead of str instance
>>>
```

### PR DESCRIPTION
**Pull request by rfk**
This should fix #45 based on @tarekziade suggestion; Tarek can you please sanity-check whether this works for you?  I don't have my OSX machine handy

### CODE REVIEW

**Comment by shnode** [comment]
jesus, this will cause a `NameError` in Python3 'cause  unicode dos not exist in Python3

**Comment by rfk** [comment]
> jesus

Please be civil.

> this will cause a NameError in Python3 'cause unicode dos not exist in Python3

It shouldn't, the file imports a special "unicode" helper from `enchant.utils` precisely to avoid this problem.  Was it throwing an error for you?

**Comment by shnode** [comment]
I'm Sorry for my incivility. 

I din't notice the util.And for this problem, it's just the code here and 1.6.6 in pypi are not in the same version.

Your modification works indeed and more clean than handle it partially.

**Comment by rfk** [comment]
> the code here and 1.6.6 ( latest ) in pypi are not in the same version.

Whoops, I guess I need to cut a new release, thanks for the reminder :-)

**Pull request merged**
